before_script:
  - git submodule update --init --recursive
  - git clone ${CONFIG_REPO} ${CONFIG_DIR}
  - chmod +x ${SCRIPT_DEPLOY}
  - source ${SCRIPT_DEPLOY}

stages:
  - build
  - deploy
  - clean

build_staging:
  stage: build
  script:
    - build staging
  tags:
    - cs_monitoring
  only:
    - dev
    - tags

deploy_staging:
  stage: deploy
  script:
    - deploy staging
  tags:
    - cs_monitoring
  only:
    - dev
    - tags

clean:
  stage: clean
  script:
    - clean
  when: always
  tags:
    - cs_monitoring
  only:
    - dev
    - tags

build_production:
  stage: build
  script:
    - build prod
  tags:
    - cs_app
  only:
    - master
    - tags

deploy_production:
  stage: deploy
  script:
    - deploy prod
  tags:
    - cs_app
  only:
    - master
    - tags

