FROM node:14.16.0

WORKDIR /app

RUN groupadd -r cystack && useradd -m -r -g cystack -s /usr/sbin/nologin -c "CyStack user" cystack

COPY ./src/ /app

COPY package.jon /app

RUN npm install pm2 -g

RUN yarn install

RUN yarn run build-web

EXPOSE 3000

ENV HOST 0.0.0.0

USER cystack

CMD ["yarn", "run", "start-web"]
