FROM node:14.16.0

WORKDIR /app

RUN groupadd -r cystack && useradd -m -r -g cystack -s /usr/sbin/nologin -c "CyStack user" cystack

RUN npm install pm2 -g

COPY . /app

RUN sed -i 's/import \* as hrtime/import hrtime/g' /app/src/renderer/jslib/src/services/consoleLog.service.ts

RUN cat /app/src/renderer/jslib/src/services/consoleLog.service.ts

RUN yarn install

RUN yarn run build-web

EXPOSE 3011

ENV HOST 0.0.0.0

USER cystack

CMD ["yarn", "run", "start-web"]
