FROM node:14.16.0

WORKDIR /app

RUN groupadd -r cystack && useradd -m -r -g cystack -s /usr/sbin/nologin -c "CyStack user" cystack

RUN npm install pm2 -g

COPY . /app

RUN yarn

ENV NODE_ENV=production

ENV CS_ENVIRONMENT=staging

ENV BASE_URL=https://locker.staging.cystack.org

ENV BASE_ID_URL=https://id.cystack.net

ENV BASE_API_URL=https://gateway.staging.cystack.org/v3

ENV WS_URL=wss://gateway.staging.cystack.org/ws

RUN yarn run build-web

ENV HOST 0.0.0.0

USER cystack

CMD ["yarn", "run", "start-web"]
